AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  news-aisummary

  Sample SAM Template for news-aisummary

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
    MemorySize: 4096
    EphemeralStorage: 
      Size: 10240

Resources:
  ScheduledLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Role: !GetAtt ScheduledLambdaFunctionRole.Arn
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 0 * * ? *)
            Name: DailySchedule
            Description: Trigger the Lambda function daily
            Enabled: true
    Metadata:
      DockerTag: news-aisummary
      DockerContext: .
      Dockerfile: Dockerfile

  ScheduledLambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBFullAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: "*"
        - PolicyName: BedrockInvokePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: bedrock:InvokeModel
                Resource: "*"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api

  ScheduledLambdaFunction:
    Description: "Schedule Lambda Function ARN"
    Value: !GetAtt ScheduledLambdaFunction.Arn
  ScheduledLambdaFunctionIamRole:
    Description: "Implicit IAM Role created for ScheduledLambdaFunction"
    Value: !GetAtt ScheduledLambdaFunctionRole.Arn
